### ISSUE TITLE
Runtime: I  don't know why the time consumption is basically the same as   f-pointnet(baseline)  0.011-0.015 s  

### ISSUE THREAD

**Issue by yiyiyin** [horizon-research/Efficient-Deep-Learning-for-Point-Clouds#14]

**Comment by yiyiyin** [comment]
I use the code test_time.py

**Comment by YuFengUofR** [comment]
I don't know where is "test_time.py", if you mentioned test_runtime.py. It depends on what gpu you used. If you used something like Nvidia 1080, there is no speedup, because the network is quite light-compute, tthe GPU resource is good enough for both baseline and our new method. If you want to see the difference, change the code to make the batch_size to be a big number, like 16, you will see the speedup. Our method targets on mobile devices like TX2. If you test on those devices, you will see the significant speedup.

**Comment by yiyiyin** [comment]
I understand. Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "horizon-research/Efficient-Deep-Learning-for-Point-Clouds"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 晚上9:15
收件人:&nbsp;"horizon-research/Efficient-Deep-Learning-for-Point-Clouds"<Efficient-Deep-Learning-for-Point-Clouds@noreply.github.com&gt;;
抄送:&nbsp;"3143056486"<3143056486@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [horizon-research/Efficient-Deep-Learning-for-Point-Clouds] Runtime: I  don't know why the time consumption is basically the same as   f-pointnet(baseline)  0.011-0.015 s   (#14)





 
I don't know where is "test_time.py", if you mentioned test_runtime.py. It depends on what gpu you used. If you used something like Nvidia 1080, there is no speedup, because the network is quite light-compute, tthe GPU resource is good enough for both baseline and our new method. If you want to see the difference, change the code to make the batch_size to be a big number, like 16, you will see the speedup. Our method targets on mobile devices like TX2. If you test on those devices, you will see the significant speedup.
